# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  app.elasticsearch.index_name:  city


services:
    app.elasticsearch:
        class:       AppBundle\AutocompleteBundle\ElasticsearchClient
        arguments:    ['%app.elasticsearch.index_name%']